### ISSUE TITLE
Clarifying expected BaseIndexer behavior for users

### ISSUE THREAD

**Issue by mroeschke** [twosigma/pandas#9]
Continuing this discussion @jreback: https://github.com/twosigma/pandas/pull/5#discussion_r308205211

Currently the `BaseIndexer` is (essentially):

```
class BaseIndexer(abc.ABC):

    def __init__(...)
         self.index = ...
         ...
     @abc.abstractmethod
     def get_window_bounds(...)
         ...
```
 
So I am expecting users to create:

```
class MyCustomIndexer(BaseIndexer):

     def __init_(...):
         ...
     def get_window_bounds(...)
         #my custom logic
```

And use like:

```
indexer = MyCustomIndexer(index=..., keys=....)
df.rolling(indexer, ...).mean()
```

So I think we're talking about the same expected behavior (I may have been unclear when I said "directly instantiate it [MyCustomIndexer]")?

**Comment by jreback** [comment]
yes this looks fine to me. My point is we *want* folks to actually make a subclass rather than directly using BaseIndexer. So I think good here.

**Comment by mroeschke** [comment]
Definitely, agreed. Glad we're on the same page 👍
